import {
  Search,
  Menu,
  X,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  ChevronUp,
  Copy,
  Check,
  Sun,
  Moon,
  ExternalLink,
  ArrowRight,
  ArrowLeft,
  List,
  Info,
  AlertTriangle,
  Lightbulb,
  PlusCircle,
  ArrowLeftCircle,
  Mail,
  Loader2,
  Lock,
  Eye,
  EyeOff,
  LogOut,
  Pencil,
  Plus,
  FilePlus,
  FolderPlus,
  Trash2,
  Upload,
  HelpCircle,
  SlidersHorizontal,
  FlaskConical,
  Zap,
  Settings,
  Save,
} from '@lucide/vue'

export const icons = {
  search: Search,
  menu: Menu,
  close: X,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronUp: ChevronUp,
  copy: Copy,
  check: Check,
  sun: Sun,
  moon: Moon,
  externalLink: ExternalLink,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  list: List,
  info: Info,
  alertTriangle: AlertTriangle,
  lightbulb: Lightbulb,
  plusCircle: PlusCircle,
  arrowLeftCircle: ArrowLeftCircle,
  mail: Mail,
  loader: Loader2,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  logOut: LogOut,
  pencil: Pencil,
  plus: Plus,
  filePlus: FilePlus,
  folderPlus: FolderPlus,
  trash: Trash2,
  upload: Upload,
  helpCircle: HelpCircle,
  sliders: SlidersHorizontal,
  flask: FlaskConical,
  zap: Zap,
  settings: Settings,
  save: Save,
} as const

export type IconName = keyof typeof icons
